xpaths = {
    "phone_number":"(//span[text()='Mobile Number or Email']/following::input)[1]",
    "full_name":"(//span[text()='Full Name']/following::input)[1]",
    "username":"(//span[text()='Username']/following::input)[1]",
    "password":"//input[@type='password']",
    "submit":'//button[@type="submit"]',
    "change_number":"/html/body/div[1]/section/main/div/article/div/div[1]/div/div/div/div[2]/button[1]",
    "change_number_submit":"/html/body/div[1]/section/main/div/article/div/div[1]/div/div/form/div[2]/button",
    "login_username":"/html/body/div[1]/section/main/article/div[2]/div[1]/div/form/div/div[1]/div/label/input",
    "login_password":"/html/body/div[1]/section/main/article/div[2]/div[1]/div/form/div/div[2]/div/label/input",
    "login_submit":"/html/body/div[1]/section/main/article/div[2]/div[1]/div/form/div/div[3]/button",
    "login_info_notnow":"/html/body/div[1]/section/main/div/div/div/div/button",
    "notification_notnow":"/html/body/div[4]/div/div/div/div[3]/button[2]",
    "profile_picture":"/html/body/div[1]/section/main/div/header/div/div/div/button",
    "follow_1":'//*[@id="react-root"]/section/main/div/header/section/div[2]/div/div/div/button',
    "follow_2":'//*[@id="react-root"]/section/main/div/header/section/div[2]/div/div/div/div/span/span[1]/button',
    "bio":'//*[@id="pepBio"]',
    "bio_submit":'//*[@id="react-root"]/section/main/div/article/form/div[10]/div/div/button',
    "privet_tik":'//*[@id="accountPrivacy"]/label/div',
    "android_login":'//*[@id="react-root"]/section/main/article/div/div/div/div[2]/button',
    "android_username_1":'//*[@id="loginForm"]/div[1]/div[1]/div/label/input',
    "android_password_1":'//*[@id="loginForm"]/div[1]/div[2]/div/label/input',
    "android_username_2":'//*[@id="loginForm"]/div[1]/div[3]/div/label/input',
    "android_password_2":'//*[@id="loginForm"]/div[1]/div[4]/div/label/input',
    "android_submit_1":'//*[@id="loginForm"]/div[1]/div[6]/button',
    "android_submit_2":'//*[@id="loginForm"]/div[1]/div[4]/button',
    "android_info_notnow":'//*[@id="react-root"]/section/main/div/div/div/button',
    "android_homescreen_notnow":"/html/body/div[4]/div/div/div/div[3]/button[2]",
    "android_send_photo":'//*[@id="react-root"]/section/nav[2]/div/div/div[2]/div/div/div[3]',
    "android_send_photo_next":'//*[@id="react-root"]/section/div[1]/header/div/div[2]/button',
    "android_send_photo_caption":'//*[@id="react-root"]/section/div[2]/section[1]/div[1]/textarea',
    "android_send_photo_share":'//*[@id="react-root"]/section/div[1]/header/div/div[2]/button',
    "android_save_photo":'//*[@id="react-root"]/section/div[1]/header/div/div[2]/button',
}